<script>
    export let nav = undefined;
</script>

<div
    class:loadingio-spinner-modal={nav == true}
    class="loadingio-spinner-bar-chart-1sgcnmb5f3d"
>
    <div class="ldio-yo1ym2j89t">
        <div>
            <div />
            <div />
            <div />
            <div />
        </div>
    </div>
</div>

<style>
    @keyframes ldio-yo1ym2j89t {
        0% {
            height: 110.00000000000001px;
        }
        33.33% {
            height: 154px;
        }
        66.66% {
            height: 66px;
        }
        100% {
            height: 110.00000000000001px;
        }
    }
    .ldio-yo1ym2j89t {
        transform-origin: 220px 220px !important;
    }
    .ldio-yo1ym2j89t > div {
        transform: rotate(180deg);
        width: 100%;
        height: 100%;
    }
    .ldio-yo1ym2j89t > div > div {
        position: absolute;
        width: 17px;
        height: 88px;
        animation: ldio-yo1ym2j89t 1s cubic-bezier(0.5, 0, 0.5, 1) infinite;
    }
    .ldio-yo1ym2j89t > div > div:nth-child(1) {
        left: 27.500000000000004px;
        background: #26a0a7;
        animation-delay: -1s;
    }
    .ldio-yo1ym2j89t > div > div:nth-child(2) {
        left: 57.500000000000004px;
        background: #d76c6c;
        animation-delay: -0.8s;
    }
    .ldio-yo1ym2j89t > div > div:nth-child(3) {
        left: 87.50000000000001px;
        background: #4d6474;
        animation-delay: -1.2s;
    }
    .ldio-yo1ym2j89t > div > div:nth-child(4) {
        left: 117.50000000000001px;
        background: #70ba6e;
        animation-delay: -1.6s;
    }
    .loadingio-spinner-bar-chart-1sgcnmb5f3d {
        width: 140px;
        height: 150px;
        display: inline-block;
        overflow: hidden;
        background: none;
        position: absolute;
        top: 50%;
        left: 50%;
        margin-left: -70px;
        margin-top: -75px;
    }
    .ldio-yo1ym2j89t {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
    }
    .ldio-yo1ym2j89t div {
        box-sizing: content-box;
    }
    .loadingio-spinner-modal {
        left: 65% !important;
    }
    /* generated by https://loading.io/ */
</style>
